name: Linux build

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository.
      uses: actions/checkout@v2

    - name: Install MUSL
      run: sudo apt install -y musl-dev musl-tools

    - name: Install MUSL target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Package agent.
      run: make build-linux-musl

